image: markhobson/maven-chrome:jdk-17

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  script:
    - mvn $MAVEN_OPTS clean package
    - mvn compile

test:
  stage: test
  script:
    - mvn surefire:test -Dtest=MyTestDemo
    - "cp -R recordings/* target/"
  artifacts:
    paths:
      - target/*




